### ISSUE TITLE
some misspelt and css issues(text-shadow)

### ISSUE THREAD

**Issue by jJayyyyyyy** [luoyan35714/LessOrMore#1]
Hi~
刚接触Jekyll，首先非常感谢你的LessOrMore~
试用了一下，发现一些小问题~
- `配置`这一节中的`_config.xml`是否笔误呢(`_config.yml`)
- [博客](http://www.hifreud.com/2016/08/26/how-to-use-this-jekyll-theme/)右上角的`关于`，点开后的列表(Github, 关于作者, 我的书单, 推荐博客, RSS订阅, 本项目)的字体看起来是模糊的。在移动端/PC端收窄浏览器还好，因为背景会变成深色的，所以不凑近看不出字体模糊。但是在PC端浏览器最大化时，背景为白色，字体模糊就比较明显了。
  
  使用开发者工具检查后，发现是样式中的 `text-shadow` 造成的，建议将 `/style/css/index.css` 中第2784行开始的 `.dropdown-menu > li > a {...}` 的最后加上一行，将原来默认的 `text-shadow` 覆盖掉，也即：
  
  ``` css
  .dropdown-menu > li > a {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.42857143;
  color: #333333;
  white-space: nowrap;
  text-shadow: none;    /*add this line*/
  }
  ```
- `执行`中的`jekyll server`，按照jekyll的Docs应该是`jekyll serve`的，不过貌似两者都能运行。。不知道是否为历史遗留问题。。
- `致谢`中，`Less官网`的链接貌似没有指向`http://lesscss.cn`，[博客](http://www.hifreud.com/2016/08/26/how-to-use-this-jekyll-theme/)中指向了文章本身，而[github repo](https://github.com/luoyan35714/LessOrMore)指向了一个404的页面。
